name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-22.04
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: default packages version
        run: |
          node -v
          npm -v
      - name: install pnpm & print version
        run: | 
          npm install -g pnpm
          pnpm --version
          
